# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmmetadata.ui'
#
# Created: Thu Oct  7 00:31:53 2010
#      by: PyQt4 UI code generator 4.7.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ConfirmMetadataDialog(object):
    def setupUi(self, ConfirmMetadataDialog):
        ConfirmMetadataDialog.setObjectName(_fromUtf8("ConfirmMetadataDialog"))
        ConfirmMetadataDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfirmMetadataDialog.resize(392, 602)
        ConfirmMetadataDialog.setModal(False)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ConfirmMetadataDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(ConfirmMetadataDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(28, 128, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 4, 1)
        self.artistLineEdit = QtGui.QLineEdit(ConfirmMetadataDialog)
        self.artistLineEdit.setObjectName(_fromUtf8("artistLineEdit"))
        self.gridLayout.addWidget(self.artistLineEdit, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateEdit = QtGui.QDateEdit(ConfirmMetadataDialog)
        self.dateEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.locationLineEdit = QtGui.QLineEdit(ConfirmMetadataDialog)
        self.locationLineEdit.setObjectName(_fromUtf8("locationLineEdit"))
        self.gridLayout.addWidget(self.locationLineEdit, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.venueLineEdit = QtGui.QLineEdit(ConfirmMetadataDialog)
        self.venueLineEdit.setObjectName(_fromUtf8("venueLineEdit"))
        self.gridLayout.addWidget(self.venueLineEdit, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 2)
        self.titleLineEdit = QtGui.QLineEdit(ConfirmMetadataDialog)
        self.titleLineEdit.setObjectName(_fromUtf8("titleLineEdit"))
        self.gridLayout.addWidget(self.titleLineEdit, 4, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tracklistTableWidget = QtGui.QTableWidget(ConfirmMetadataDialog)
        self.tracklistTableWidget.setColumnCount(0)
        self.tracklistTableWidget.setObjectName(_fromUtf8("tracklistTableWidget"))
        self.tracklistTableWidget.setColumnCount(0)
        self.tracklistTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tracklistTableWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_6 = QtGui.QLabel(ConfirmMetadataDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.commentsTextEdit = QtGui.QTextEdit(ConfirmMetadataDialog)
        self.commentsTextEdit.setObjectName(_fromUtf8("commentsTextEdit"))
        self.verticalLayout_2.addWidget(self.commentsTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton = QtGui.QPushButton(ConfirmMetadataDialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem6 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.artistLineEdit)
        self.label_2.setBuddy(self.dateEdit)
        self.label_3.setBuddy(self.locationLineEdit)
        self.label_4.setBuddy(self.venueLineEdit)
        self.label_7.setBuddy(self.titleLineEdit)
        self.label_5.setBuddy(self.tracklistTableWidget)
        self.label_6.setBuddy(self.commentsTextEdit)

        self.retranslateUi(ConfirmMetadataDialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ConfirmMetadataDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(ConfirmMetadataDialog)

    def retranslateUi(self, ConfirmMetadataDialog):
        ConfirmMetadataDialog.setWindowTitle(QtGui.QApplication.translate("ConfirmMetadataDialog", "Confirm Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "&Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "&Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setDisplayFormat(QtGui.QApplication.translate("ConfirmMetadataDialog", "MMMM dd, yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "&Location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "&Venue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "Title &Override", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "&Tracklist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ConfirmMetadataDialog", "Next", None, QtGui.QApplication.UnicodeUTF8))

