# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Fri Feb 18 21:39:57 2011
#      by: PyQt4 UI code generator 4.7.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.setWindowModality(QtCore.Qt.WindowModal)
        SettingsDialog.resize(425, 387)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtGui.QGridLayout(SettingsDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(SettingsDialog)
        self.label_4.setToolTip(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.addToITunesPathTextEdit = QtGui.QTextEdit(SettingsDialog)
        self.addToITunesPathTextEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addToITunesPathTextEdit.sizePolicy().hasHeightForWidth())
        self.addToITunesPathTextEdit.setSizePolicy(sizePolicy)
        self.addToITunesPathTextEdit.setMaximumSize(QtCore.QSize(5000, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.addToITunesPathTextEdit.setPalette(palette)
        self.addToITunesPathTextEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.addToITunesPathTextEdit.setObjectName(_fromUtf8("addToITunesPathTextEdit"))
        self.gridLayout_2.addWidget(self.addToITunesPathTextEdit, 0, 1, 2, 2)
        self.changeAddToITunesPathButton = QtGui.QPushButton(SettingsDialog)
        self.changeAddToITunesPathButton.setObjectName(_fromUtf8("changeAddToITunesPathButton"))
        self.gridLayout_2.addWidget(self.changeAddToITunesPathButton, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(SettingsDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setMargin(0)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.albumTitleFormatLineEdit = QtGui.QLineEdit(SettingsDialog)
        self.albumTitleFormatLineEdit.setObjectName(_fromUtf8("albumTitleFormatLineEdit"))
        self.gridLayout_2.addWidget(self.albumTitleFormatLineEdit, 2, 1, 1, 2)
        self.label_3 = QtGui.QLabel(SettingsDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.dateFormatComboBox = QtGui.QComboBox(SettingsDialog)
        self.dateFormatComboBox.setObjectName(_fromUtf8("dateFormatComboBox"))
        self.gridLayout_2.addWidget(self.dateFormatComboBox, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        self.label = QtGui.QLabel(SettingsDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.defaultArtRadioButtonIdenticon = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonIdenticon.setObjectName(_fromUtf8("defaultArtRadioButtonIdenticon"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonIdenticon)
        self.defaultArtRadioButtonVisicon = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonVisicon.setObjectName(_fromUtf8("defaultArtRadioButtonVisicon"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonVisicon)
        self.defaultArtRadioButtonNoCoverArt = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonNoCoverArt.setObjectName(_fromUtf8("defaultArtRadioButtonNoCoverArt"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonNoCoverArt)
        self.defaultArtRadioButtonImageFileIdenticon = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonImageFileIdenticon.setObjectName(_fromUtf8("defaultArtRadioButtonImageFileIdenticon"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonImageFileIdenticon)
        self.defaultArtRadioButtonImageFileVisicon = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonImageFileVisicon.setObjectName(_fromUtf8("defaultArtRadioButtonImageFileVisicon"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonImageFileVisicon)
        self.defaultArtRadioButtonImageFileNoCoverArt = QtGui.QRadioButton(SettingsDialog)
        self.defaultArtRadioButtonImageFileNoCoverArt.setObjectName(_fromUtf8("defaultArtRadioButtonImageFileNoCoverArt"))
        self.verticalLayout.addWidget(self.defaultArtRadioButtonImageFileNoCoverArt)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 1, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.checkForUpdatesCheckBox = QtGui.QCheckBox(SettingsDialog)
        self.checkForUpdatesCheckBox.setObjectName(_fromUtf8("checkForUpdatesCheckBox"))
        self.gridLayout.addWidget(self.checkForUpdatesCheckBox, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.sendErrorReportsCheckBox = QtGui.QCheckBox(SettingsDialog)
        self.sendErrorReportsCheckBox.setToolTip(_fromUtf8(""))
        self.sendErrorReportsCheckBox.setObjectName(_fromUtf8("sendErrorReportsCheckBox"))
        self.gridLayout.addWidget(self.sendErrorReportsCheckBox, 1, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton = QtGui.QPushButton(SettingsDialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        spacerItem6 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 0, 1, 3)

        self.retranslateUi(SettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialog.reject)
        QtCore.QObject.connect(self.changeAddToITunesPathButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.changeAddToITunesPath)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsDialog.restoreDefaults)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(QtGui.QApplication.translate("SettingsDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SettingsDialog", "\"Add to iTunes\" Path", None, QtGui.QApplication.UnicodeUTF8))
        self.changeAddToITunesPathButton.setText(QtGui.QApplication.translate("SettingsDialog", "Change Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsDialog", "Album Title Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SettingsDialog", "Date Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingsDialog", "Default Cover Art", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonIdenticon.setToolTip(QtGui.QApplication.translate("SettingsDialog", "A unique design based on the recording\'s text file.  Single-colored.", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonIdenticon.setText(QtGui.QApplication.translate("SettingsDialog", "Identicon", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonVisicon.setToolTip(QtGui.QApplication.translate("SettingsDialog", "A unique design based on the recording\'s text file.  Two-colored.", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonVisicon.setText(QtGui.QApplication.translate("SettingsDialog", "Visicon", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonNoCoverArt.setText(QtGui.QApplication.translate("SettingsDialog", "No Cover Art", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonImageFileIdenticon.setText(QtGui.QApplication.translate("SettingsDialog", "Image File (fallback to Identicon)", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonImageFileVisicon.setText(QtGui.QApplication.translate("SettingsDialog", "Image File (fallback to Visicon)", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultArtRadioButtonImageFileNoCoverArt.setText(QtGui.QApplication.translate("SettingsDialog", "Image File (fallback to No Cover Art)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkForUpdatesCheckBox.setText(QtGui.QApplication.translate("SettingsDialog", "Check For Updates On Startup", None, QtGui.QApplication.UnicodeUTF8))
        self.sendErrorReportsCheckBox.setText(QtGui.QApplication.translate("SettingsDialog", "Send Error Reports To Developer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("SettingsDialog", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))

