"""
This is a setup.py script generated by py2applet, but then tweaked to get it to work.

Usage:
    python setup-mac.py py2app
"""

from setuptools import setup

import os
os.system("rm -rf dist")
os.system("rm -rf build")

NAME = 'BootTunes'
VERSION = '1.0.0'

APP = ['boottunes.pyw']
DATA_FILES = ['data']
OPTIONS = {
    'argv_emulation': False,
    'includes': ['sip', 'PyQt4.QtGui', 'PyQt4.QtCore'],
    'iconfile': 'data/media/logo.icns',
    'plist'   : {'CFBundleName': NAME,
                 'CFShortVersionString': VERSION,
                 'CFBundleGetInfoString': ' '.join([NAME, VERSION]),
                 'CFBundleExecutable': NAME,
                 'CFBundleIdentifier': 'com.chavezsoft.BootTunes'}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# Need to add to the system path
file = open('dist/BootTunes.app/Contents/Resources/__boot__.py', 'r')
bootContents = file.read()
file = open('dist/BootTunes.app/Contents/Resources/__boot__.py', 'w')
file.write("""import os, sys \nsys.path = [os.path.join(
    os.environ['RESOURCEPATH'], 'lib', 'python2.6', 'lib-dynload')] + sys.path\n""" + bootContents
)
# Create empty qt.conf file to prevent "...loading two sets of Qt binaries..." error.
open('dist/boottunes.app/Contents/Resources/qt.conf', 'w')
# Delete unneeded files
os.system("rm -f dist/BootTunes.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore_debug")
os.system("rm -f dist/BootTunes.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui_debug")